#!/usr//bin/python
import argparse
import socket

target_host = "localhost"
target_port = 43
LF = '\r\n'

def parse_args():
    parser = argparse.ArgumentParser(description='nra-whois parser')
    parser.add_argument('--get', nargs='?')
    args = parser.parse_args()
    return args

def main():
    args = parse_args()
    resource = args.get + LF
    # create a socket object
    client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    # connect the client
    client.connect((target_host,target_port))
    # send object
    client.send(resource)
    # receive some data
    response = client.recv(4096)
    print response


if __name__ == '__main__':
    main()
